version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./html:/usr/share/nginx/html:ro
      - ./data/letsencrypt:/etc/letsencrypt:ro
      - ./html/certbot-challenge:/var/www/certbot:ro
      - ./logs/nginx:/var/log/nginx
    labels:
      - "auto-renew=true"

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    restart: unless-stopped
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/letsencrypt:/etc/letsencrypt
      - ./html/certbot-challenge:/var/www/certbot
      - ./certbot/config:/etc/letsencrypt/renewal
      - ./certbot/logs:/var/log/letsencrypt
volumes:
  letsencrypt-data:
    driver: local
    driver_opts:
      type: none
      device: ./data/letsencrypt
      o: bind
